# Generated by Django 3.1.2 on 2020-10-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0021_auto_20200724_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehichle',
            old_name='shop_name',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='rentvehichle',
            name='hdstatus',
        ),
        migrations.RemoveField(
            model_name='rentvehichle',
            name='shop_registration',
        ),
    ]
