# Generated by Django 3.1.2 on 2020-10-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0022_auto_20201027_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentvehichle',
            name='dept_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
