# Generated by Django 3.1.2 on 2020-10-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0023_auto_20201027_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentvehichle',
            old_name='ownername',
            new_name='fullname',
        ),
    ]
